version: '3.8'
services:
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    environment:
      RABBIT_URI : amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - currency-network
  currency-exchange:
    image: sayan0306/currency-exchange-service:0.0.1
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT : http://zipkin-server:9411/api/v2/spans
      RABBIT_URI : amqp://guest:guest@rabbitmq:5672
      SPRING_ZIPKIN_SENDER_TYPE : rabbit
#      SPRING.RABBITMQ.HOST : rabbitmq
#      SPRING.ZIPKIN.SENDER.TYPE : rabbit
#      RABBIT-URL : amqp://guest@rabbitmq:5672
#      SPRING_RABBITMQ-HOST : rabbitmq

  naming-server:
    image: sayan0306/namingserver:0.0.1
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-conversion:
    image: sayan0306/currency-conversion-service:0.0.1
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT : http://zipkin-server:9411/api/v2/spans
      RABBIT_URI : amqp://guest:guest@rabbitmq:5672
      SPRING_ZIPKIN_SENDER_TYPE : rabbit

#      SPRING.RABBITMQ.HOST : rabbitmq
#      SPRING.ZIPKIN.SENDER.TYPE : rabbit
  api-gateway:
    image: sayan0306/api-gateway:0.0.1
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT : http://zipkin-server:9411/api/v2/spans
      RABBIT_URI : amqp://guest:guest@rabbitmq:5672
      SPRING_ZIPKIN_SENDER_TYPE : rabbit
#      SPRING.RABBITMQ.HOST : rabbitmq
#      SPRING.ZIPKIN.SENDER.TYPE : rabbit
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    #amqp
      - "15672:15672"  #http
      - "15692:15692"  #prometheus
      - "25672:25672"  #clustering
    networks:
      currency-network:
networks:
  currency-network:
